name: build

on:
  push:
    branches:
      - "main"

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "cachix/cachix-action@v12"
        with:
          name: modupdate
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
